const data = {
  products: [
    {
      name: "Nike Slim shirt",
      slug: "nike-slim-shirt",
      category: "Shirt",
      image: "/image/p1.jpg",
      price: 120,
      countInStock: 10,
      brand: "Nike",
      rating: 4.5,
      numReviews: 10,
      description: "High Qulity Shirt",
    },
    {
      name: "Adidas fit shirt",
      slug: "adidas-slim-shirt",
      category: "Shirt",
      image: "/image/p2.jpg",
      price: 250,
      countInStock: 20,
      brand: "Adidas",
      rating: 3,
      numReviews: 10,
      description: "High Qulity Shirt",
    },
    {
      name: "Nike Slim Pant",
      slug: "nike-slim-pant",
      category: "Pant",
      image: "/image/p2.jpg",
      price: 1200,
      countInStock: 100,
      brand: "Nike",
      rating: 2,
      numReviews: 10,
      description: "High Qulity Shirt",
    },
    {
      name: "adidas fit pant",
      slug: "adidas-fit-pant",
      category: "pant",
      image: "/image/p4.jpg",
      price: 65,
      countInStock: 10,
      brand: "adidas",
      rating: 1.5,
      numReviews: 10,
      description: "High Qulity Shirt",
    },
  ],
};

export default data;
